import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const pkg=fs.readdirSync('node_modules/.pnpm').find(p=>p.startsWith('miniflare@'));
const {Miniflare}=await import(path.resolve('node_modules/.pnpm',pkg,'node_modules/miniflare/dist/src/index.js'));
function collect(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?collect(path.join(dir,e.name)):e.name.endsWith('.js')?[path.join(dir,e.name)]:[])}
const files=collect('dist/server').sort((a,b)=>a==='dist/server/index.js'?-1:b==='dist/server/index.js'?1:a.localeCompare(b));
const mf=new Miniflare({modules:files.map(p=>({type:'ESModule',path:path.resolve(p)})),modulesRoot:path.resolve('dist/server'),outboundService:async(req)=>{assert.equal(new URL(req.url).hostname,'api.example.com');assert.equal(req.headers.get('Authorization'),'Bearer test-secret-key-1234');const body=await req.json();return Response.json({choices:[{message:{content:body.messages[0].content.includes('JSON 数组')?JSON.stringify([{front:'测试 AI 问题',back:'测试 AI 答案'}]):'# 测试 AI 整理\n\n二阶矩是梯度平方的指数加权平均。'}}]})},compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'test-db'},r2Buckets:{BUCKET:'test-bucket'},bindings:{APP_SECRET:'test-only-encryption-secret-not-for-production'},assets:{directory:path.resolve('dist/client'),binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}},log:undefined});
const owner={userId:'test-owner',email:'owner@example.com'},editor={userId:'test-editor',email:'editor@example.com'},viewer={userId:'test-viewer',email:'viewer@example.com'},stranger={userId:'test-stranger',email:'stranger@example.com'};
function headers(user){return user?{'oai-authenticated-user-id':user.userId,'oai-authenticated-user-email':user.email}:{};}
async function call(user,action,data={},method='POST',expected=200){const url='https://workspace.test/api/workspace'+(method==='GET'?'?'+new URLSearchParams({action,...data}):'');const r=await mf.dispatchFetch(url,{method,headers:{...headers(user),...(method==='POST'?{'Content-Type':'application/json'}:{})},...(method==='POST'?{body:JSON.stringify({action,...data})}:{})});const responseText=await r.text();if(!responseText)throw new Error(action+" returned empty body: "+r.status+" "+r.headers.get("location"));let json;try{json=JSON.parse(responseText)}catch{throw new Error(action+" invalid JSON: "+r.status+" "+responseText.slice(0,500))};assert.equal(r.status,expected,action+': '+JSON.stringify(json));return json;}
try{
const db=await mf.getD1Database('DB');const sql=fs.readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort().map(n=>fs.readFileSync('drizzle/'+n,'utf8')).join('\n');for(const statement of sql.split(';').map(x=>x.replaceAll('--> statement-breakpoint','').trim()).filter(Boolean)){if(statement.startsWith('ALTER TABLE `users`'))await db.prepare('INSERT INTO users(id,name,email,created_at) VALUES(?,?,?,?)').bind('legacy-user','旧用户','legacy@example.com',new Date().toISOString()).run();await db.prepare(statement).run()}assert.equal((await db.prepare('SELECT onboarding_step FROM users WHERE id=?').bind('legacy-user').first()).onboarding_step,-1);
await call(null,'bootstrap',{},'GET',401);
const initial=await call(owner,'bootstrap',{},'GET');const space=initial.space;assert.equal(initial.pages.length,0);assert.equal(initial.subjects.length,0);assert.equal(initial.generations.length,0);assert.equal(initial.onboardingStep,0);
await call(owner,'onboarding',{step:2});assert.equal((await call(owner,'bootstrap',{},'GET')).onboardingStep,2);await call(owner,'onboarding',{step:4},'POST',400);await call(owner,'onboarding',{step:-1});assert.equal((await call(owner,'bootstrap',{},'GET')).onboardingStep,-1);
const repeat=await call(owner,'bootstrap',{},'GET');assert.equal(repeat.space,space);assert.equal(repeat.spaces.length,1);
const subject=await call(owner,'subject',{space,name:'验证学科'});const page=await call(owner,'create',{space,subject:subject.id,title:'API integration test',template:'PyTorch'});const read=await call(owner,'page',{id:page.id},'GET');assert.equal(read.blocks.length,12);
const bs=[{id:crypto.randomUUID(),type:'text',content:{text:'MarkerNeedle 这里是笔记内容'}},{id:crypto.randomUUID(),type:'code',content:{language:'python',code:'print("MarkerCode")'}},{id:crypto.randomUUID(),type:'html',content:{html:'<h1>test</h1>',css:'h1{color:blue}',js:'console.log("hello")'}}];
await call(owner,'save',{id:page.id,title:'保存验证',blocks:bs,tags:['测试标签'],version:1});
await call(owner,'save',{id:page.id,title:'不应覆盖',blocks:[],tags:[],version:1},'POST',409);
const saved=await call(owner,'page',{id:page.id},'GET');assert.equal(saved.page.version,2);assert.equal(saved.blocks.length,3);assert.deepEqual(saved.tags,['测试标签']);assert.equal(saved.revisions.length,2);
assert((await call(owner,'search',{space,q:'MarkerCode'},'GET')).some(p=>p.id===page.id));assert((await call(owner,'search',{space,q:'测试标签'},'GET')).some(p=>p.id===page.id));
await call(owner,'comment',{id:page.id,blockId:bs[0].id,content:'这里为什么要平方？',kind:'修改建议'});const comments=await call(owner,'page',{id:page.id},'GET');assert.equal(comments.comments.length,1);const cid=comments.comments[0].id;
await call(owner,'comment',{id:page.id,parentId:cid,content:'用于二阶矩估计。'});await call(owner,'like',{id:cid});await call(owner,'like',{id:cid});const liked=await call(owner,'page',{id:page.id},'GET');assert.equal(liked.comments[0].likes,0);
await call(owner,'cards',{id:page.id,cards:[{front:'二阶矩是什么？',back:'梯度平方的指数加权平均'}]});let cards=await call(owner,'review',{space},'GET');assert.equal(cards.length,1);await call(owner,'review',{id:cards[0].id,rating:'不记得'});assert.equal((await call(owner,'review',{space},'GET')).length,0);
await call(owner,'progress',{id:page.id,status:'需要复习',importance:1,mastery:35,nextReview:new Date(Date.now()-3600000).toISOString()});const progress=(await call(owner,'page',{id:page.id},'GET')).progress;assert.equal(progress.mastery,35);
const newUser=await call(stranger,'bootstrap',{},'GET');assert.equal(newUser.pages.length,0);assert.equal(newUser.subjects.length,0);assert.equal(newUser.onboardingStep,0);assert.equal((await call(owner,'bootstrap',{},'GET')).onboardingStep,-1);await call(stranger,'page',{id:page.id},'GET',403);await call(stranger,'search',{space,q:'test'},'GET',403);
await call(owner,'invite',{space,email:editor.email,role:'Editor'});const ed=await call(editor,'bootstrap',{},'GET');assert(ed.spaces.some(s=>s.id===space));await call(editor,'comment',{id:page.id,content:'编辑者已加入'});
await call(owner,'invite',{space,email:viewer.email,role:'Viewer'});await call(viewer,'bootstrap',{},'GET');await call(viewer,'create',{space,title:'权限越界'},'POST',403);await call(viewer,'comment',{id:page.id,content:'不应成功'},'POST',403);await call(viewer,'page',{id:page.id},'GET');await call(editor,'invite',{space,email:'third@example.com',role:'Editor'},'POST',403);
await call(owner,'provider',{name:'测试兼容网关',baseUrl:'https://api.example.com/v1',model:'test-model',key:'test-secret-key-1234'});const providers=(await call(owner,'bootstrap',{space},'GET')).providers;assert.equal(providers[0].key_hint,'1234');assert(!JSON.stringify(providers).includes('test-secret'));const enc=await db.prepare('SELECT encrypted_key FROM ai_providers').first();assert(!enc.encrypted_key.includes('test-secret-key'));assert.equal((await call(editor,'bootstrap',{space},'GET')).providers.length,0);
const generated=await call(owner,'ai',{id:page.id,aiAction:'总结笔记'});assert(generated.output.includes('二阶矩'));const beforeAI=await call(owner,'page',{id:page.id},'GET');assert.equal(beforeAI.blocks.length,3);assert.equal(beforeAI.generations[0].status,'草稿');await call(owner,'acceptGeneration',{id:generated.id});assert.equal((await call(owner,'page',{id:page.id},'GET')).generations[0].status,'已采纳');const generatedCards=await call(owner,'ai',{id:page.id,aiAction:'生成知识卡片'});assert(Array.isArray(JSON.parse(generatedCards.output)));
await call(owner,'provider',{name:'private',baseUrl:'http://localhost:1234/v1',model:'test',key:'x'},'POST',400);await call(editor,'ai',{id:page.id,aiAction:'总结笔记'},'POST',400);
const form=new FormData();form.set('space',space);form.set('file',new File([new Uint8Array([137,80,78,71,13,10,26,10])],'test.png',{type:'image/png'}));const encoded=new Request('https://workspace.test/api/upload',{method:'POST',body:form});const uploaded=await mf.dispatchFetch('https://workspace.test/api/upload',{method:'POST',headers:{...headers(owner),'Content-Type':encoded.headers.get('content-type')},body:new Uint8Array(await encoded.arrayBuffer())});assert.equal(uploaded.status,200);const asset=await uploaded.json();const assetRead=await mf.dispatchFetch('https://workspace.test'+asset.url,{headers:headers(owner)});assert.equal(assetRead.status,200);assert.equal((await assetRead.arrayBuffer()).byteLength,8);const denied=await mf.dispatchFetch('https://workspace.test'+asset.url,{headers:headers(stranger)});assert.equal(denied.status,403);
async function importFile(user,path,contents,settings={},expected=200){const form=new FormData();form.set('space',space);form.set('path',path);form.set('file',new File([contents],path.split('/').at(-1)));for(const [k,v] of Object.entries(settings))form.set(k,v);const encoded=new Request('https://workspace.test/api/import',{method:'POST',body:form});const r=await mf.dispatchFetch(encoded.url,{method:'POST',headers:{...headers(user),'Content-Type':encoded.headers.get('content-type')},body:new Uint8Array(await encoded.arrayBuffer())});const out=await r.json();assert.equal(r.status,expected,JSON.stringify(out));return out}
const imported=await importFile(owner,'PyTorch/基础/examples/train.py','print("ImportNeedle")');const importedRead=await call(owner,'page',{id:imported.id},'GET');assert.equal(importedRead.page.file_type,'code');assert.equal(importedRead.page.source_path,'PyTorch/基础/examples/train.py');assert.equal(importedRead.blocks[0].content.language,'python');assert.equal(importedRead.blocks[0].content.code,'print("ImportNeedle")');const original=await mf.dispatchFetch('https://workspace.test/api/assets/'+imported.assetId,{headers:headers(owner)});assert.equal(await original.text(),'print("ImportNeedle")');
const tree=(await call(owner,'bootstrap',{space},'GET')).pages;assert.equal(tree.find(p=>p.id===imported.parent).title,'code');const codeFolder=tree.find(p=>p.id===imported.parent),examples=tree.find(p=>p.id===codeFolder.parent_id);assert.equal(examples.title,'examples');assert.equal(tree.find(p=>p.id===examples.parent_id).title,'基础');const dup=await importFile(owner,'PyTorch/基础/examples/train.py','print(2)');assert.equal(dup.title,'train (2).py');assert.equal(dup.parent,imported.parent);
const doc=await importFile(owner,'PyTorch/基础/参考.md','# 参考\n\n学习资料');assert.equal((await call(owner,'page',{id:doc.id},'GET')).blocks[0].type,'markdown');assert.equal((await call(owner,'bootstrap',{space},'GET')).pages.find(p=>p.id===doc.parent).title,'文档');
const categorized=await importFile(owner,'PyTorch/code/models/conv.py','import torch');const categorizedTree=(await call(owner,'bootstrap',{space},'GET')).pages;assert.equal(categorizedTree.find(p=>p.id===categorized.parent).title,'models');const explicit=await importFile(owner,'PyTorch/docs/reference.md','# Reference',{subject:imported.subject});const et=(await call(owner,'bootstrap',{space},'GET')).pages;assert.equal(et.find(p=>p.id===explicit.parent).title,'docs');assert.equal(et.find(p=>p.id===explicit.parent).parent_id,null);
const notebook=await importFile(owner,'PyTorch/lesson.ipynb',JSON.stringify({metadata:{kernelspec:{language:'python'}},cells:[{cell_type:'markdown',source:['# Notebook']},{cell_type:'code',source:['print(3)'],execution_count:1,outputs:[{output_type:'stream',text:['3\n']}]}]}));const nr=await call(owner,'page',{id:notebook.id},'GET');assert.equal(nr.blocks.length,2);assert.equal(nr.blocks[1].content.output,'3\n');assert.equal(nr.page.file_type,'notebook');
const plotbook=await importFile(owner,'plot.ipynb',JSON.stringify({cells:[{cell_type:'code',source:['plot()'],outputs:[{data:{'image/png':'iVBORw0KGgo='}}]}]}));const pr=await call(owner,'page',{id:plotbook.id},'GET');assert.equal(pr.blocks[1].type,'image');assert(pr.blocks[1].content.url.startsWith('/api/assets/'));
const exported={format:'zhixu-note',schemaVersion:1,page:{title:'恢复的笔记',fileType:'note'},tags:['测试','测试'],blocks:[{id:'old-id',type:'text',collapsed:true,content:{text:'ExportRoundTrip'}},{id:'old-image',type:'image',content:{url:'data:image/png;base64,iVBORw0KGgo=',name:'test.png'}}]};const restored=await importFile(owner,'restored.json',JSON.stringify(exported));const rr=await call(owner,'page',{id:restored.id},'GET');assert.equal(rr.page.title,'恢复的笔记');assert.equal(rr.blocks[0].content.text,'ExportRoundTrip');assert(rr.blocks[0].collapsed);assert.notEqual(rr.blocks[0].id,'old-id');assert(rr.blocks[1].content.url.startsWith('/api/assets/'));assert.deepEqual(rr.tags,['测试']);const restoredImage=await mf.dispatchFetch('https://workspace.test'+rr.blocks[1].content.url,{headers:headers(owner)});assert.equal(restoredImage.status,200);
await importFile(viewer,'forbidden.py','print(0)',{},403);await importFile(owner,'../outside.py','print(0)',{},400);assert((await call(owner,'search',{space,q:'ImportNeedle'},'GET')).some(p=>p.id===imported.id));
await call(owner,'organizePage',{id:examples.id,parent:imported.parent,title:examples.title,version:examples.version},'POST',400);await call(owner,'organizePage',{id:imported.id,parent:doc.parent,title:'renamed.py',fileType:'code',version:1});const moved=await call(owner,'page',{id:imported.id},'GET');assert.equal(moved.page.parent_id,doc.parent);assert.equal(moved.page.title,'renamed.py');assert.equal(moved.page.version,2);await call(owner,'organizePage',{id:imported.id,title:'stale',version:1},'POST',409);
console.log('PASS: hierarchical file import, original downloads, code/doc categorization, duplicate preservation, Notebook cells/outputs, JSON round-trip resources, traversal rejection, role checks and cycle-safe versioned moves.');
const r=await call(owner,'revision',{id:saved.revisions.find(r=>r.version===1).id},'GET');await call(owner,'save',{id:page.id,title:r.snapshot.title,blocks:r.snapshot.blocks,tags:r.snapshot.tags,version:2});assert.equal((await call(owner,'page',{id:page.id},'GET')).page.version,3);
const sample=await call(owner,'create',{space,title:'真实关联目标'});await call(owner,'link',{id:page.id,target:sample.id,relation:'前置知识'});assert((await call(owner,'page',{id:sample.id},'GET')).links.some(l=>l.from_id===page.id));
await call(owner,'deletePage',{id:page.id});await call(owner,'page',{id:page.id},'GET',404);assert(!(await call(owner,'search',{space,q:'MarkerCode'},'GET')).some(p=>p.id===page.id));
const home=await mf.dispatchFetch('https://workspace.test/',{headers:headers(owner)});assert.equal(home.status,200);const html=await home.text();assert(html.includes('知序'));
console.log('PASS: auth, bootstrap, spaces, subjects, blocks, persistence, conflict, tags, search, comments, replies, likes, revisions, rollback, cards, reviews, progress, roles, tenant isolation, encrypted providers, key isolation, invalid endpoints, uploads, asset access, backlinks and SSR.');
}finally{await mf.dispose()}
