import fs from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
async function source(name){const js=ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'))}
const f=await source('lib/files.ts'),m=await source('lib/mindmap.ts');
assert.equal(f.classifyFile('train.PY'),'code');assert.equal(f.classifyFile('资料.pdf'),'document');assert.equal(f.classifyFile('lesson.ipynb'),'notebook');assert.deepEqual(f.safeImportPath('pytorch\\basics\\code\\train.py'),['pytorch','basics','code','train.py']);for(const p of ['../secrets','/root/code.py','x/../../x','C:\\secrets','x//x'])assert.throws(()=>f.safeImportPath(p));
const md=f.noteMarkdown('测试',[{id:'1',type:'code',content:{code:'print("```")',language:'python',output:'saved'}},{id:'2',type:'todo',content:{done:true,text:'复习'}},{id:'3',type:'mindmap',content:{nodes:[{id:'root',text:'Adam'},{id:'1',parent:'root',text:'一阶矩'}]}}],['优化器']);assert(md.includes('````python'));assert(md.includes('- [x] 复习'));assert(md.includes('  - 一阶矩'));
const nodes=[{id:'root',text:'Root',x:0,y:0},{id:'a',parent:'root',text:'子主题 A',x:0,y:0},{id:'b',parent:'root',text:'B',x:0,y:0},{id:'a1',parent:'a',text:'孙主题',x:0,y:0},{id:'a2',parent:'a',text:'孙主题 2',x:0,y:0}];for(const layout of ['逻辑图','树状图','中心主题']){const laid=m.layoutNodes(nodes,layout);assert(laid.every(n=>Number.isFinite(n.x)&&Number.isFinite(n.y)));assert.equal(new Set(laid.map(n=>n.x+','+n.y)).size,5)}assert.equal(m.visibleNodes(nodes.map(n=>n.id==='a'?{...n,collapsed:true}:n)).length,3);assert.deepEqual([...m.descendants(nodes,'a')].sort(),['a','a1','a2']);assert.strictEqual(m.reparentNode(nodes,'a','a1'),nodes);assert.equal(m.reparentNode(nodes,'a1','b').find(n=>n.id==='a1').parent,'b');
console.log('PASS: file classification, traversal rejection, Markdown code fences, Todo, mindmap export, map layouts, collapse and safe reparenting.');
