import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {randomBytes,createHash} from 'node:crypto';
import {startService} from '../out/service.mjs';
const base=path.resolve(import.meta.dirname,'..');
test('Local account, knowledge persistence, non-mutating index, references and isolation',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'zhixu-test-')),dataDir=path.join(dir,'data'),rootDir=path.join(dir,'PyTorch'),code=path.join(rootDir,'code','train.py'),doc=path.join(rootDir,'docs','reference.md');await fs.mkdir(path.dirname(code),{recursive:true});await fs.mkdir(path.dirname(doc),{recursive:true});await fs.writeFile(code,'print("original")\n');await fs.writeFile(doc,'# Reference\n');const before=await fs.stat(code),digest=await fs.readFile(code),secret=randomBytes(32).toString('hex');let service=await startService({dataDir,secret,migrations:path.join(base,'out/migrations'),renderer:path.join(base,'out/renderer')}),cookie='';
 async function request(url,body,status=200,extra={}){const r=await fetch(service.origin+url,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),cookie,...extra},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();assert.equal(r.status,status,JSON.stringify(result));if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return result}
 const workspace=(action,data={})=>request('/api/workspace',{action,...data});
 try{assert.equal((await request('/local/auth/status')).setupRequired,true);await request('/api/workspace?action=bootstrap',null,401);await request('/local/auth/setup',{username:'学生',password:'correct-password-123'});assert.equal((await request('/local/auth/status')).user.fullName,'学生');await request('/local/auth/setup',{username:'other',password:'long-password'},409);const boot=await request('/api/workspace?action=bootstrap');assert.equal(boot.pages.length,0);const space=boot.space;
 const created=await workspace('create',{space,title:'本地笔记',blockType:'text'});await workspace('save',{id:created.id,title:'持久化内容',version:1,tags:['重点'],blocks:[{id:'block-test',type:'text',content:{text:'SQLite persistent note'}}]});assert.equal((await request('/api/workspace?action=page&id='+created.id)).blocks[0].content.text,'SQLite persistent note');
 const grant=service.indexer.grantRootPath(rootDir),scan=await request('/local/index/start',{grant,space});await service.indexer.wait(scan.id);let rows=(await request('/local/index/files?root='+scan.id)).files;assert.equal(rows.length,2);const file=rows.find(f=>f.name==='train.py');assert.equal(file.file_type,'code');await request('/local/index/classify',{root:scan.id,id:file.id,subject:'PyTorch',folder:'优化器 / 代码',tags:['重点']});assert.equal((await request('/local/index/content?id='+file.id)).text,digest.toString());assert.deepEqual(await fs.readFile(code),digest);assert.equal((await fs.stat(code)).mtimeMs,before.mtimeMs);assert.equal((await fs.readdir(path.dirname(code))).join(','),'train.py');assert.equal((await request('/local/index/files?root='+scan.id+'&q=优化器')).files.length,1);
 await request('/local/index/refresh',{root:scan.id});await service.indexer.wait(scan.id);rows=(await request('/local/index/files?root='+scan.id)).files;assert.equal(rows.find(f=>f.id===file.id).subject,'PyTorch');await fs.unlink(doc);await request('/local/index/refresh',{root:scan.id});await service.indexer.wait(scan.id);assert.equal((await request('/local/index/files?root='+scan.id)).files.find(f=>f.name==='reference.md').status,'missing');
 await request('/local/index/start',{grant,space},400);const cross=await fetch(service.origin+'/local/auth/status',{headers:{Origin:'https://evil.example'}});assert.equal(cross.status,403);await request('/local/auth/logout',{});await request('/local/auth/login',{username:'学生',password:'incorrect-password'},401);await request('/api/workspace?action=bootstrap',null,401,{'oai-authenticated-user-id':'spoof','oai-authenticated-user-email':'spoof@local.invalid'});await request('/local/auth/login',{username:'学生',password:'correct-password-123'});
 const stored=service.db.sqlite.prepare('SELECT * FROM local_accounts').get();assert.notEqual(stored.password_hash,'correct-password-123');assert.equal(stored.password_hash.length,128);assert(!stored.salt.includes('password'));
 await service.close();service=await startService({dataDir,secret,migrations:path.join(base,'out/migrations'),renderer:path.join(base,'out/renderer')});await request('/local/auth/login',{username:'学生',password:'correct-password-123'});assert.equal((await request('/api/workspace?action=page&id='+created.id)).page.title,'持久化内容');assert.equal((await request('/local/index/roots')).length,1);assert.equal((await request('/local/index/files?root='+scan.id)).files.find(f=>f.id===file.id).virtual_folder,'优化器 / 代码');const html=await fetch(service.origin);assert.equal(html.status,200);assert((await html.text()).includes('本地学习工作台'));
 }finally{await service.close();await fs.rm(dir,{recursive:true,force:true})}});
