'use client';
import {BookOpen,Folder,Upload,Sparkles,Clock} from 'lucide-react';
import {Btn,Modal} from './ui';
import {Progress} from '@/components/ui/progress';
const steps=[
 {title:'先给知识一个位置',icon:Folder,text:'你的学习空间已经准备好了。你可以按学科整理，也可以直接导入本地文件夹，沿用原有目录。',tips:['在知识库中添加“PyTorch”等学科；目录箭头可以展开层级。','侧栏可以收起成图标，打开笔记不会自动收回。'],action:'添加第一个学科'},
 {title:'从你的第一篇笔记开始',icon:BookOpen,text:'新建一页，把概念、代码、图片与公式放在一起。也可以直接导入已有资料。',tips:['点击“添加内容块”，插入代码、图片、HTML 实验或思维导图。','修改后点击“保存修改”。文本框会随内容自动调整高度。','导入文件夹会保留层级；Notebook 可导入单元格与已有输出，Python 在本地运行。'],action:'创建第一篇笔记'},
 {title:'连接自己的 AI 助手',icon:Sparkles,text:'在设置中填写兼容接口的地址、API Key 和模型名称，再回到笔记中打开 AI 整理。暂时不需要 AI，也可以跳过。',tips:['AI 可以总结笔记、解释代码、生成卡片或思维导图。','生成结果先作为草稿展示，由你决定追加还是替换。','API Key 加密保存，不会显示完整密钥。'],action:'打开 AI 设置'},
 {title:'把知识留住，定期回来复习',icon:Clock,text:'在笔记中标记学习状态，点击“明日复习”安排复习。需要带走内容时，从右上角导出笔记。',tips:['“学习模式”隐藏编辑控件，方便专注阅读。','Ctrl / ⌘ + K 可以搜索标题、内容、代码和标签。','Markdown 便于阅读；JSON 保存内容块，支持重新导入。'],action:'打开复习页面'}
];
export function UsageGuide({open,onClose,step,onStep,onAction,busy,canEdit}:any){const current=steps[step]||steps[0],Icon=current.icon;return <Modal open={open} onClose={onClose} title="开始使用知序" description="这里从空知识库开始，所有内容由你创建或导入。"><div className="usage-guide"><div className="guide-progress"><span>{step+1} / {steps.length}</span><Progress value={(step+1)/steps.length*100}/></div><div className="guide-icon"><Icon size={28}/></div><h2>{current.title}</h2><p>{current.text}</p><ul>{current.tips.map(t=><li key={t}>{t}</li>)}</ul><Btn className="w-full" disabled={busy} onClick={()=>onAction(canEdit?step:-1)}>{canEdit?current.action:'浏览当前知识库'}</Btn>{!canEdit&&<p className="small muted">当前空间为只读。你可以阅读与复习，或从顶部空间菜单创建自己的空间。</p>}<div className="guide-footer"><button className="text-btn" disabled={busy} onClick={()=>onStep(-1)}>跳过引导</button><div className="row">{step>0&&<Btn disabled={busy} onClick={()=>onStep(step-1)}>上一步</Btn>}<Btn primary disabled={busy} onClick={()=>onStep(step===3?-1:step+1)}>{step===3?'完成引导':'下一步'}</Btn></div></div></div></Modal>}
export function GettingStarted({canEdit,onCreate,onImport,onSubject,onGuide}:any){return <section className="getting-started"><div className="getting-started-heading"><div><span className="eyebrow">从这里开始</span><h2>你的知识库还是空的。</h2><p>写下第一个知识点，或把已有学习资料带进来。</p></div><button className="text-btn" onClick={onGuide}>查看使用引导</button></div><div className="getting-started-actions"><button disabled={!canEdit} onClick={onCreate}><BookOpen size={22}/><strong>新建笔记</strong><span>文字、代码、公式与图片</span></button><button disabled={!canEdit} onClick={onImport}><Upload size={22}/><strong>导入资料</strong><span>文件、文件夹或 Notebook</span></button><button disabled={!canEdit} onClick={onSubject}><Folder size={22}/><strong>创建学科</strong><span>按自己的学习路径分类</span></button></div>{!canEdit&&<p className="muted">当前空间仅可阅读，可从顶部空间菜单创建自己的知识空间。</p>}</section>}
