'use client';
import {useEffect,useRef,useState} from 'react';
import {RotateCw,Undo2,ZoomIn,ZoomOut} from 'lucide-react';
import {Modal,Choice,Btn} from './ui';
import {toast} from 'sonner';
const tools=['自由画笔','箭头','矩形','圆形','文本','高亮','马赛克','序号','裁剪'];
export function ImageEditor({image,onClose,onSave}:{image:any;onClose:()=>void;onSave:(blob:Blob)=>Promise<void>}){const canvas=useRef<HTMLCanvasElement>(null),history=useRef<string[]>([]),start=useRef<any>(null),[tool,setTool]=useState('箭头'),[color,setColor]=useState('#2875e8'),[width,setWidth]=useState(4),[caption,setCaption]=useState('知识点'),[zoom,setZoom]=useState(1),[busy,setBusy]=useState(false),number=useRef(1),loaded=useRef(false);
function remember(){if(canvas.current){history.current.push(canvas.current.toDataURL());if(history.current.length>20)history.current.shift()}}
useEffect(()=>{const img=new Image();img.onload=()=>{const c=canvas.current;if(!c)return;const scale=Math.min(1,1600/img.width);c.width=img.width*scale;c.height=img.height*scale;c.getContext('2d')!.drawImage(img,0,0,c.width,c.height);loaded.current=true};img.onerror=()=>toast.error('图片加载失败');img.src=image.url},[image.url]);
function point(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return {x:(e.clientX-r.left)*e.currentTarget.width/r.width,y:(e.clientY-r.top)*e.currentTarget.height/r.height}}
function draw(e:React.PointerEvent<HTMLCanvasElement>,finish=false){const c=canvas.current,s=start.current;if(!c||!s)return;const p=point(e),ctx=c.getContext('2d')!;if(tool==='自由画笔'||tool==='高亮'){ctx.strokeStyle=color;ctx.lineWidth=tool==='高亮'?width*5:width;ctx.lineCap='round';ctx.globalAlpha=tool==='高亮'?.2:1;ctx.beginPath();ctx.moveTo(s.last.x,s.last.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.globalAlpha=1;s.last=p;return}ctx.putImageData(s.snapshot,0,0);ctx.strokeStyle=tool==='裁剪'?'#ffffff':color;ctx.fillStyle=color;ctx.lineWidth=width;ctx.lineCap='round';const dx=p.x-s.x,dy=p.y-s.y;ctx.beginPath();if(tool==='矩形'||tool==='裁剪'){if(tool==='裁剪')ctx.setLineDash([8,8]);ctx.strokeRect(s.x,s.y,dx,dy);ctx.setLineDash([])}if(tool==='圆形'){ctx.ellipse(s.x+dx/2,s.y+dy/2,Math.abs(dx/2),Math.abs(dy/2),0,0,Math.PI*2);ctx.stroke()}if(tool==='箭头'){ctx.moveTo(s.x,s.y);ctx.lineTo(p.x,p.y);const a=Math.atan2(dy,dx),len=20;ctx.moveTo(p.x-len*Math.cos(a-.5),p.y-len*Math.sin(a-.5));ctx.lineTo(p.x,p.y);ctx.lineTo(p.x-len*Math.cos(a+.5),p.y-len*Math.sin(a+.5));ctx.stroke()}if(tool==='马赛克'){const x=Math.max(0,Math.min(s.x,p.x)),y=Math.max(0,Math.min(s.y,p.y)),w=Math.min(c.width-x,Math.abs(dx)),h=Math.min(c.height-y,Math.abs(dy));for(let xx=x;xx<x+w;xx+=14)for(let yy=y;yy<y+h;yy+=14){const px=ctx.getImageData(Math.floor(xx),Math.floor(yy),1,1).data;ctx.fillStyle=`rgb(${px[0]},${px[1]},${px[2]})`;ctx.fillRect(xx,yy,Math.min(14,x+w-xx),Math.min(14,y+h-yy))}}if(finish&&tool==='裁剪'){ctx.putImageData(s.snapshot,0,0);const x=Math.max(0,Math.min(s.x,p.x)),y=Math.max(0,Math.min(s.y,p.y)),w=Math.min(c.width-x,Math.abs(dx)),h=Math.min(c.height-y,Math.abs(dy));if(w>10&&h>10){const img=ctx.getImageData(x,y,w,h);c.width=w;c.height=h;c.getContext('2d')!.putImageData(img,0,0)}}}
async function save(){const c=canvas.current;if(!c||!loaded.current)return;setBusy(true);try{const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('导出失败')),'image/png'));await onSave(blob);onClose()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
return <Modal open title="标注学习截图" description="保存为新图片，原图会保留。拖动鼠标或手指完成标注。" onClose={onClose} wide><div className="row wrap"><Choice value={tool} items={tools} onChange={setTool}/><input type="color" aria-label="标注颜色" value={color} onChange={e=>setColor(e.target.value)}/><input type="range" aria-label="笔画粗细" min="2" max="12" value={width} onChange={e=>setWidth(+e.target.value)}/>{tool==='文本'&&<input aria-label="标注文字" value={caption} onChange={e=>setCaption(e.target.value)}/>}<Btn title="旋转 90 度" onClick={()=>{const c=canvas.current;if(!c)return;remember();const temp=document.createElement('canvas');temp.width=c.width;temp.height=c.height;temp.getContext('2d')!.drawImage(c,0,0);c.width=temp.height;c.height=temp.width;const ctx=c.getContext('2d')!;ctx.translate(c.width/2,c.height/2);ctx.rotate(Math.PI/2);ctx.drawImage(temp,-temp.width/2,-temp.height/2);ctx.setTransform(1,0,0,1,0,0)}}><RotateCw size={16}/></Btn><Btn title="撤销" onClick={()=>{const src=history.current.pop();if(!src)return;const img=new Image();img.onload=()=>{const c=canvas.current!;c.width=img.width;c.height=img.height;c.getContext('2d')!.drawImage(img,0,0)};img.src=src}}><Undo2 size={16}/></Btn><Btn title="缩小" onClick={()=>setZoom(Math.max(.25,zoom-.25))}><ZoomOut size={16}/></Btn><Btn title="放大" onClick={()=>setZoom(Math.min(3,zoom+.25))}><ZoomIn size={16}/></Btn></div><div className="image-canvas-scroll"><canvas ref={canvas} style={{width:zoom*100+'%',touchAction:'none'}} onPointerDown={e=>{if(!loaded.current)return;const c=e.currentTarget,ctx=c.getContext('2d')!,p=point(e);remember();c.setPointerCapture(e.pointerId);if(tool==='文本'){ctx.fillStyle=color;ctx.font=`${Math.max(20,width*7)}px sans-serif`;ctx.fillText(caption,p.x,p.y);return}if(tool==='序号'){ctx.fillStyle=color;ctx.beginPath();ctx.arc(p.x,p.y,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='white';ctx.textAlign='center';ctx.font='bold 22px sans-serif';ctx.fillText(String(number.current++),p.x,p.y+8);ctx.textAlign='left';return}start.current={...p,last:p,snapshot:ctx.getImageData(0,0,c.width,c.height)}}} onPointerMove={e=>draw(e)} onPointerUp={e=>{draw(e,true);start.current=null}} onPointerCancel={()=>start.current=null}/></div><div className="row end"><Btn onClick={onClose}>取消</Btn><Btn primary disabled={busy} onClick={save}>{busy?'正在保存…':'保存标注图片'}</Btn></div></Modal>}
