import {scrypt,randomBytes,randomUUID,createHash,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';
const derive=promisify(scrypt),hash=s=>createHash('sha256').update(s).digest('hex');
export function localAuth(sqlite){const attempts=new Map();const cookieName='zhixu_local_session';
 const profile=id=>{const u=sqlite.prepare('SELECT id,name,email FROM users WHERE id=?').get(id);return u?{userId:u.id,email:u.email,fullName:u.name,displayName:u.name}:null};
 const token=req=>{const value=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='));return value?.slice(cookieName.length+1)||''};
 const user=req=>{const t=token(req);if(!/^[a-f0-9]{64}$/.test(t))return null;const s=sqlite.prepare('SELECT user_id FROM local_sessions WHERE token_hash=? AND expires_at>?').get(hash(t),Date.now());return s?profile(s.user_id):null};
 async function handle(req){const pathname=new URL(req.url).pathname;const first=sqlite.prepare('SELECT COUNT(*) AS count FROM local_accounts').get().count===0;if(req.method==='GET'&&pathname==='/local/auth/status')return Response.json({setupRequired:first,user:user(req)});if(req.method!=='POST')return Response.json({error:'方法不正确'},{status:405});
 if(pathname==='/local/auth/logout'){sqlite.prepare('DELETE FROM local_sessions WHERE token_hash=?').run(hash(token(req)));return Response.json({ok:true},{headers:{'Set-Cookie':`${cookieName}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0`}})}
 const body=await req.json(),username=typeof body.username==='string'?body.username.trim().toLowerCase():'',password=body.password;if(!/^[\p{L}\p{N}_-]{2,40}$/u.test(username)||typeof password!=='string'||password.length<8||password.length>128)return Response.json({error:'账户名为 2–40 个字母、汉字、数字或下划线；密码为 8–128 位。'},{status:400});
 if(pathname==='/local/auth/setup'){if(!first)return Response.json({error:'本机已经设置账户，请登录。'},{status:409});const salt=randomBytes(32).toString('hex'),digest=Buffer.from(await derive(password,salt,64)).toString('hex'),id=randomUUID();sqlite.exec('BEGIN IMMEDIATE');try{if(sqlite.prepare('SELECT COUNT(*) AS count FROM local_accounts').get().count)throw new Error('本机已经设置账户');sqlite.prepare('INSERT INTO users(id,name,email,created_at) VALUES(?,?,?,?)').run(id,username,username+'@local.invalid',new Date().toISOString());sqlite.prepare('INSERT INTO local_accounts(user_id,username,salt,password_hash) VALUES(?,?,?,?)').run(id,username,salt,digest);sqlite.exec('COMMIT')}catch(e){sqlite.exec('ROLLBACK');throw e}}
 else if(pathname!=='/local/auth/login')return Response.json({error:'未知操作'},{status:404});
 const throttle=attempts.get(username)||{count:0,until:0};if(throttle.until>Date.now())return Response.json({error:'尝试次数过多，请 30 秒后重试。'},{status:429});const account=sqlite.prepare('SELECT * FROM local_accounts WHERE username=?').get(username),salt=account?.salt||'unregistered-account-salt',digest=Buffer.from(await derive(password,salt,64));if(!account||!timingSafeEqual(digest,Buffer.from(account.password_hash,'hex'))){attempts.set(username,{count:throttle.count+1,until:throttle.count>=4?Date.now()+30000:0});return Response.json({error:'账户或密码不正确。'},{status:401})}attempts.delete(username);const t=randomBytes(32).toString('hex');sqlite.prepare('DELETE FROM local_sessions WHERE expires_at<=?').run(Date.now());sqlite.prepare('INSERT INTO local_sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(hash(t),account.user_id,Date.now()+8*3600000);return Response.json({user:profile(account.user_id)},{headers:{'Set-Cookie':`${cookieName}=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`}})}
 return {user,handle}
}
