import fs from 'node:fs/promises';
import path from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {setImmediate as yieldEventLoop} from 'node:timers/promises';
const ignored=new Set(['node_modules','.git','.svn','.idea','.venv','venv','__pycache__','.next','dist']);
const groups={py:'code',java:'code',c:'code',h:'code',cpp:'code',js:'code',ts:'code',tsx:'code',jsx:'code',html:'code',css:'code',sql:'code',json:'code',yaml:'code',yml:'code',sh:'code',ps1:'code',ipynb:'notebook',md:'document',txt:'document',pdf:'document',doc:'document',docx:'document',ppt:'document',pptx:'document',csv:'document',xls:'document',xlsx:'document',png:'image',jpg:'image',jpeg:'image',gif:'image',webp:'image'};
const type=name=>groups[name.toLowerCase().split('.').at(-1)]||'other';
export function createIndexer(sqlite){const grants=new Map(),jobs=new Map();
 const rootFor=(id,user)=>sqlite.prepare('SELECT * FROM indexed_roots WHERE id=? AND user_id=?').get(id,user.userId);
 const fileFor=(id,user)=>sqlite.prepare('SELECT f.*,r.path AS root_path,r.user_id,r.space_id FROM indexed_files f JOIN indexed_roots r ON r.id=f.root_id WHERE f.id=? AND r.user_id=?').get(id,user.userId);
 function grantRootPath(directory){const id=randomUUID();grants.set(id,{path:directory,expires:Date.now()+60000});return id}
 async function start(root){if(jobs.has(root.id))throw new Error('此目录正在建立索引');const controller=new AbortController(),scan=randomUUID();jobs.set(root.id,{controller});sqlite.prepare("UPDATE indexed_roots SET status='scanning',message='',scanned_count=0 WHERE id=?").run(root.id);const promise=(async()=>{let count=0,skipped=0;try{const rootPath=await fs.realpath(root.path);if(!(await fs.stat(rootPath)).isDirectory())throw new Error('目录不可用');const stack=[''];while(stack.length){if(controller.signal.aborted)throw new Error('扫描已暂停');const relative=stack.pop();let directory;try{directory=await fs.opendir(path.join(rootPath,relative))}catch{skipped++;continue}for await(const entry of directory){if(controller.signal.aborted)throw new Error('扫描已暂停');if(entry.isSymbolicLink()){skipped++;continue}if(entry.isDirectory()){if(!ignored.has(entry.name))stack.push(path.join(relative,entry.name));continue}if(!entry.isFile())continue;const rel=path.join(relative,entry.name);let info;try{info=await fs.stat(path.join(rootPath,rel))}catch{skipped++;continue}const id=createHash('sha256').update(root.id+'|'+rel).digest('hex');sqlite.prepare("INSERT INTO indexed_files(id,root_id,relative_path,name,file_type,size,mtime,status,seen_scan) VALUES(?,?,?,?,?,?,?,'available',?) ON CONFLICT(root_id,relative_path) DO UPDATE SET size=excluded.size,mtime=excluded.mtime,file_type=excluded.file_type,status='available',seen_scan=excluded.seen_scan").run(id,root.id,rel,entry.name,type(entry.name),info.size,info.mtimeMs,scan);count++;if(count%50===0){sqlite.prepare('UPDATE indexed_roots SET scanned_count=? WHERE id=?').run(count,root.id);await yieldEventLoop()}if(count>=50000)throw new Error('每个目录最多索引 50,000 个文件，请选择更小的目录')}}sqlite.prepare("UPDATE indexed_files SET status='missing' WHERE root_id=? AND seen_scan<>?").run(root.id,scan);sqlite.prepare("UPDATE indexed_roots SET status='ready',message=?,scanned_count=?,last_scan=? WHERE id=?").run(skipped?'已跳过 '+skipped+' 个链接或不可读目录':'',count,new Date().toISOString(),root.id)}catch(e){sqlite.prepare('UPDATE indexed_roots SET status=?,message=?,scanned_count=? WHERE id=?').run(controller.signal.aborted?'paused':'error',e.message,count,root.id)}finally{jobs.delete(root.id)}})();jobs.get(root.id).promise=promise;return root.id}
 async function safeFile(file){if(!file)throw new Error('文件不存在或无权访问');const root=await fs.realpath(file.root_path),resolved=await fs.realpath(path.resolve(root,file.relative_path));if(resolved===root||!resolved.startsWith(root+path.sep))throw new Error('文件不在授权目录中');if(!(await fs.stat(resolved)).isFile())throw new Error('原文件不可用');return resolved}
 async function handle(req,user){const url=new URL(req.url),action=url.pathname.split('/').at(-1);if(req.method==='GET'&&action==='roots')return Response.json(sqlite.prepare('SELECT * FROM indexed_roots WHERE user_id=? ORDER BY rowid').all(user.userId));if(req.method==='GET'&&action==='files'){const id=url.searchParams.get('root');if(!rootFor(id,user))return Response.json({error:'目录不存在'},{status:404});const q=(url.searchParams.get('q')||'').slice(0,200),rows=sqlite.prepare('SELECT * FROM indexed_files WHERE root_id=? ORDER BY relative_path LIMIT 5000').all(id);const filtered=q?rows.filter(f=>[f.name,f.relative_path,f.subject,f.tags,f.virtual_folder].join(' ').toLowerCase().includes(q.toLowerCase())):rows;return Response.json({files:filtered,total:sqlite.prepare('SELECT COUNT(*) AS count FROM indexed_files WHERE root_id=?').get(id).count,limit:5000})}
 if(req.method==='GET'&&action==='content'){const file=fileFor(url.searchParams.get('id'),user),location=await safeFile(file),stat=await fs.stat(location);if(stat.size>2*1024*1024)return Response.json({error:'预览限制 2 MB，请在原文件所在目录查看。'},{status:413});if(file.file_type==='other'||file.file_type==='image')return Response.json({error:'此文件不是文本预览格式'},{status:415});const raw=await fs.readFile(location);if(raw.includes(0))return Response.json({error:'此格式为二进制文件，请定位原文件查看。'},{status:415});return Response.json({text:raw.toString('utf8'),name:file.name,fileType:file.file_type})}
 if(req.method==='GET'&&action==='image'){const file=fileFor(url.searchParams.get('id'),user);if(file?.file_type!=='image')return new Response('Not found',{status:404});const location=await safeFile(file),stat=await fs.stat(location);if(stat.size>12*1024*1024)return new Response('Too large',{status:413});const mime={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp'}[file.name.toLowerCase().split('.').at(-1)];return new Response(await fs.readFile(location),{headers:{'Content-Type':mime,'X-Content-Type-Options':'nosniff','Cache-Control':'no-store'}})}
 if(req.method!=='POST')return Response.json({error:'方法不正确'},{status:405});const b=await req.json();if(action==='start'){const grant=grants.get(b.grant);grants.delete(b.grant);if(!grant||grant.expires<Date.now())throw new Error('请重新选择目录');const member=sqlite.prepare('SELECT role FROM members WHERE space_id=? AND user_id=?').get(b.space,user.userId);if(!member||!['Owner','Admin','Editor'].includes(member.role))return Response.json({error:'需要空间编辑权限'},{status:403});const location=await fs.realpath(grant.path);const existing=sqlite.prepare('SELECT * FROM indexed_roots WHERE user_id=? AND space_id=? AND path=?').get(user.userId,b.space,location);const id=existing?.id||randomUUID();if(!existing)sqlite.prepare('INSERT INTO indexed_roots(id,user_id,space_id,path,name) VALUES(?,?,?,?,?)').run(id,user.userId,b.space,location,path.basename(location));await start(rootFor(id,user));return Response.json({id})}
 const root=rootFor(b.root,user);if(!root)throw new Error('目录不存在');if(action==='refresh'){await start(root);return Response.json({ok:true})}if(action==='cancel'){jobs.get(root.id)?.controller.abort();return Response.json({ok:true})}if(action==='classify'){const f=fileFor(b.id,user);if(!f||f.root_id!==root.id)throw new Error('文件不属于此目录');const tags=Array.isArray(b.tags)?[...new Set(b.tags.filter(t=>typeof t==='string').map(t=>t.slice(0,60)))].slice(0,30):[];sqlite.prepare('UPDATE indexed_files SET subject=?,tags=?,virtual_folder=? WHERE id=?').run(String(b.subject||'').slice(0,100),JSON.stringify(tags),String(b.folder||'').slice(0,200),f.id);return Response.json({ok:true})}return Response.json({error:'未知索引操作'},{status:404})}
 return {handle,grantRootPath,fileFor,safeFile,async wait(id){await jobs.get(id)?.promise},async stop(){for(const j of jobs.values())j.controller.abort();await Promise.all([...jobs.values()].map(j=>j.promise))}}
}
