import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createDatabase} from './sqlite.mjs';
import {localAuth} from './auth.mjs';
import {createIndexer} from './indexer.mjs';
import {env} from './runtime-env.mjs';
import {requestContext} from './context.mjs';
import * as routes from './out/api.mjs';
const mime={'.html':'text/html;charset=utf-8','.js':'text/javascript;charset=utf-8','.css':'text/css;charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2','.json':'application/json'};
export async function startService({dataDir,migrations=path.join(import.meta.dirname,'migrations'),renderer=path.join(import.meta.dirname,'renderer'),secret}){await fs.mkdir(dataDir,{recursive:true});const db=createDatabase(path.join(dataDir,'knowledge.sqlite'),migrations),auth=localAuth(db.sqlite),indexer=createIndexer(db.sqlite),resourceDir=path.join(dataDir,'resources');await fs.mkdir(resourceDir,{recursive:true});
 const keyPath=key=>{if(!/^[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+$/.test(key))throw new Error('资源地址无效');return path.join(resourceDir,key)};
 env.DB=db;env.APP_SECRET=secret;env.BUCKET={async put(key,body){const file=keyPath(key);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,new Uint8Array(body))},async get(key){try{return {body:await fs.readFile(keyPath(key))}}catch(e){if(e.code==='ENOENT')return null;throw e}},async delete(key){await fs.rm(keyPath(key),{force:true})}};
 let origin;
 async function dispatch(req){const url=new URL(req.url);if(req.headers.get('host')!==new URL(origin).host)return new Response('Host not allowed',{status:403});const requestOrigin=req.headers.get('origin');if(requestOrigin&&requestOrigin!==origin)return new Response('Origin not allowed',{status:403});if(url.pathname.startsWith('/local/auth/'))return auth.handle(req);const user=auth.user(req);if(url.pathname.startsWith('/api/')||url.pathname.startsWith('/local/')){if(!user)return Response.json({error:'请先登录本地账户'},{status:401});return requestContext.run({user},async()=>{if(url.pathname==='/api/workspace'){if(!['GET','POST'].includes(req.method))return new Response('Method not allowed',{status:405});return routes.workspace[req.method](req)}if(url.pathname==='/api/upload'&&req.method==='POST')return routes.upload.POST(req);if(url.pathname==='/api/import'&&req.method==='POST')return routes.imported.POST(req);if(/^\/api\/assets\/[^/]+$/.test(url.pathname)&&req.method==='GET')return routes.assets.GET(req,{params:Promise.resolve({id:url.pathname.split('/').at(-1)})});if(url.pathname.startsWith('/local/index/'))return indexer.handle(req,user);return new Response('Not found',{status:404})})}
 if(req.method!=='GET')return new Response('Method not allowed',{status:405});const location=path.resolve(renderer,'.'+decodeURIComponent(url.pathname));if(!location.startsWith(path.resolve(renderer)+path.sep)&&location!==path.resolve(renderer))return new Response('Not found',{status:404});let file=location;try{if(!(await fs.stat(file)).isFile())file=path.join(renderer,'index.html')}catch{file=path.join(renderer,'index.html')}const contents=await fs.readFile(file);return new Response(contents,{headers:{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https: data: blob:; font-src 'self' data:; connect-src 'self'; frame-src 'self' blob:; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'",'X-Content-Type-Options':'nosniff'}})}
 const server=http.createServer(async(incoming,outgoing)=>{try{const chunks=[];let size=0;for await(const chunk of incoming){size+=chunk.length;if(size>20*1024*1024){outgoing.writeHead(413);outgoing.end('Request too large');return}chunks.push(chunk)}const req=new Request(origin+incoming.url,{method:incoming.method,headers:incoming.headers,...(!['GET','HEAD'].includes(incoming.method)?{body:Buffer.concat(chunks)}:{})});const response=await dispatch(req);outgoing.writeHead(response.status,Object.fromEntries(response.headers));outgoing.end(Buffer.from(await response.arrayBuffer()))}catch(e){outgoing.writeHead(400,{'Content-Type':'application/json'});outgoing.end(JSON.stringify({error:e.message||'本地操作失败'}))}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+server.address().port;
 return {origin,db,indexer,auth,async fileLocation(id,cookie){const user=auth.user(new Request(origin,{headers:{cookie}}));if(!user)throw new Error('请先登录');return indexer.safeFile(indexer.fileFor(id,user))},async close(){await indexer.stop();await new Promise(resolve=>server.close(resolve));db.close();env.DB=null}}
}
